server:
  port: 9000

spring:
  application:
    name: api-service
    version: 1.0.0
  mvc:
    throw-exception-if-no-handler-found: true
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true
    lease-expiration-duration-in-seconds: 30 
    lease-renewal-interval-in-seconds: 10

com:
  deswaef:
    reddit:
      url: https://www.reddit.com/r