server:
  port: 9001

spring:
  application:
    name: notification-service
    version: 1.0.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true
    lease-expiration-duration-in-seconds: 30 
    lease-renewal-interval-in-seconds: 10