server:
  port: 9110

spring:
  application:
    name: eureka-demo-notification

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9100/eureka/
    healthcheck:
      enabled: true
  instance:
    hostname: localhost
    instanceId: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    lease-expiration-duration-in-seconds: 30 
    lease-renewal-interval-in-seconds: 10

management:
  security:
    enabled: false

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
