server:
  port: 9110

spring:
  application:
    name: eureka-demo-notification

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9100/eureka/
//  instance:
//    preferIpAddress: true
