server:
  port: 9110

spring:
  application:
    name: eureka-demo-notification

management:
    security:
        enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9100/eureka/      
  instance:
    preferIpAddress: true
