server:
  port: 9120

spring:
  application:
    name: eureka-demo-user

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9100/eureka/
  instance:
    hostname: localhost
    instanceId: ${eureka.instance.hostname}:${spring.application.name}:${server.port}

management:
  security:
    enabled: false

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true